[Feature]:Changed the hamburger ui with a good animation
rbjks/rbjks.github.io pull request #116
Opened 2024-03-27 03:19 UTC by mohit-bhandari45

Fixes #114 

Description:-
Changed the hamburger animation with a proper animation.
Earlier it was sliding from the top which was not looking very good 
But changed it to right slider

How Has This Been Tested?
I have tested it by previewing it multiple times

Screenshots:
Before:-
After:-

## Types of Changes

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-04-04 11:29 UTC, adityaraute requested changes
Let us know once those changes are done

2024-04-04 11:29 UTC, adityaraute commented on index.html
> +        <a id="hamburger" href="javascript:void(0);" class="icon" onclick="toggleMobileNav()">
You've only added this on the index page, but not on the contact or activities page.
Please do so, too. This maintain consistency across all pages.
![image](https://github.com/rbjks/rbjks.github.io/assets/43912470/62683f92-313a-49b6-a9ae-1c50f723b051)

2024-04-04 11:29 UTC, adityaraute commented on index.html
> +        <a id="hamburger" href="javascript:void(0);" class="icon" onclick="toggleMobileNav()">
Try to make sure that whenever any link in the menu is clicked, the sidebar collapses.
Currently after clicking the `हिन्दी में देखिये` link or `Read in English` link, the sidebar doesn't collapse.

![image](https://github.com/rbjks/rbjks.github.io/assets/43912470/cb5fa217-ddd0-45cd-baac-997a2c500123)

2024-04-04 15:08 UTC, mohit-bhandari45 commented
it is done you can review it

2024-04-04 15:09 UTC, mohit-bhandari45 commented
it is done you can check

2024-04-05 08:53 UTC, adityaraute requested changes
You have formatted entire files with `html` and `css` code for some formatting changes.
We cannot merge such a commit. 
These many changes are not acceptable. Please fix the formatting issues and only create a PR for changes that the repo needs.


I suggest you delete this branch, and try making your changes on a new one.
![image](https://github.com/rbjks/rbjks.github.io/assets/43912470/dabb8bb6-7a10-4cd7-9ab4-8c1393679afb)

2024-04-11 10:08 UTC, adityaraute commented
Hi @mohit-bhandari45 
What's the update on this one?

2024-04-30 16:27 UTC, closed without merging