changes to css to make home page more responsive.
rbjks/rbjks.github.io pull request #125
Opened 2024-04-04 13:46 UTC by CampbellBrim

## Motivation and Context

improve responsiveness of home page

Fixes Issue #115 

## Description

Changes to make flex direction change on smaller screen sizes. Adjustments to margins. Font color changed to black

## How Has This Been Tested?

chrome dev tools responsive viewport mode

## Screenshots (if appropriate):
before:
![Captura de tela 2024-03-27 134259](https://github.com/rbjks/rbjks.github.io/assets/84410954/1dfe9e6f-55f4-447d-900a-3550f9864f9d)
After: 
![Captura de tela 2024-03-27 134226](https://github.com/rbjks/rbjks.github.io/assets/84410954/d1d3ec82-376f-49b6-8455-c92cdda17d5e)

2024-04-05 11:03 UTC, adityaraute requested changes
Apart from the stylistic changes suggested, I feel there are a lot of unnecessary changes in this PR to the style.css file. 
I would appreciate it if you could get rid of those changes and make the PR crisper.
Thanks!

2024-04-05 11:03 UTC, adityaraute commented on assets/css/style.css
> +  color: black;
Before:
![image](https://github.com/rbjks/rbjks.github.io/assets/43912470/26e4518c-0a84-481d-a439-1f0d9553c9a0)


After:
![image](https://github.com/rbjks/rbjks.github.io/assets/43912470/b6165669-791f-47b9-ab80-0ce9ce3f2cf9)

The text is too wide. I liked the previous margin settings, could you revert this change?

Also, hadn't we discussed we'd choose a shade different than black or white? Perhaps we can try a lighter shade here.

2024-04-05 11:03 UTC, adityaraute commented on assets/css/style.css
> +  .introduction {
Even in the mobile view
![image](https://github.com/rbjks/rbjks.github.io/assets/43912470/86ccde23-f7dd-46c0-a695-93d412b80730)

I'm not happy about how close the text is to the margins and the image above. Perhaps we could add some space around the text here?

2024-04-10 18:53 UTC, CampbellBrim commented
> Apart from the stylistic changes suggested, I feel there are a lot of unnecessary changes in this PR to the style.css file. I would appreciate it if you could get rid of those changes and make the PR crisper. Thanks!

When I reduced the margins it created side scrolling. I believe this was because of the header. I made multiple changes to try to remove the side scrolling, but was having a hard time understanding why there was side scrolling. I will reduce the changes.

2024-04-10 18:59 UTC, closed without merging