Fixed the footer of the website
rbjks/rbjks.github.io pull request #138
Opened 2024-04-30 18:55 UTC by mohit-bhandari45

Fixes #119

Description:-
Fixed the overall ui structure of the footer with proper backgrounds and much more

How Has This Been Tested?
I have tested the code by running it multiple times

Screenshots (if appropriate):
Before:-
![image](https://github.com/rbjks/rbjks.github.io/assets/151373021/f30c00b8-8889-4b68-89ea-7eced2b34e4a)

After:-
![image](https://github.com/rbjks/rbjks.github.io/assets/151373021/dd24c07e-42a0-4eda-a6d0-4ed475db53f0)

What types of changes does your code introduce?

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-05-06 15:33 UTC, adityaraute requested changes
I feel you are changing the footer too much.
Let's just add circular background to the icons and discard the other changes. Can we do that?

Issues:

Font size too big

![image](https://github.com/rbjks/rbjks.github.io/assets/43912470/5d78fb68-5a22-4bdd-bdcb-58d45b04bf6a)


Mobile view messed up due to the same

![image](https://github.com/rbjks/rbjks.github.io/assets/43912470/81a54133-41a7-4c73-a940-cda3892ea2e4)

2024-05-06 17:33 UTC, mohit-bhandari45 commented
![Uploading image.png…]()

Is it good now?

2024-05-06 17:36 UTC, mohit-bhandari45 commented
![image](https://github.com/rbjks/rbjks.github.io/assets/151373021/cada5f20-a95e-408f-8126-c4358f207505)

Is it good now?

2024-05-07 10:55 UTC, adityaraute commented
> ![image](https://private-user-images.githubusercontent.com/151373021/328266164-cada5f20-a95e-408f-8126-c4358f207505.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNzk1OTYsIm5iZiI6MTcxNTA3OTI5NiwicGF0aCI6Ii8xNTEzNzMwMjEvMzI4MjY2MTY0LWNhZGE1ZjIwLWE5NWUtNDA4Zi04MTI2LWM0MzU4ZjIwNzUwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwN1QxMDU0NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYTA2N2Q5ZjM0ODg3ODE1NmZjYzAyMjExNDMwMTQwOTc1NGFjOWUxZDkxNDJhYjFlYTdhZGQxMjg5Y2ViNTRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1Q-dmXHF7EjNr7AykRAV5V_uFuEWH2OggMddLdC3Ewk)
> 
> Is it good now?

This looks better. Can you also post a screenshot of the mobile view?

2024-05-07 11:43 UTC, mohit-bhandari45 commented
![image](https://github.com/rbjks/rbjks.github.io/assets/151373021/5857e2bf-7c20-4bf5-bae0-efac70c314a8)

2024-05-07 16:44 UTC, mohit-bhandari45 commented
![image](https://github.com/rbjks/rbjks.github.io/assets/151373021/560f1828-d73b-4102-a7ee-0281e36a7e93)
is it good now??

2024-05-07 16:47 UTC, adityaraute commented
Yes this looks good @mohit-bhandari45

2024-05-07 17:14 UTC, mohit-bhandari45 commented
Done changes you can check

2024-05-07 17:21 UTC, adityaraute requested changes
Now the desktop view is messed up 


![image](https://github.com/rbjks/rbjks.github.io/assets/43912470/2526bf5c-da6b-4cce-aed5-9d5b2d2df93c)

The text on the left is misaligned.


Also, I'm seeing too many unnecessary changes in files regarding formatting and linting. You should try to revert those unnecessary changes, too.

![image](https://github.com/rbjks/rbjks.github.io/assets/43912470/aafd72d5-d23d-4308-8f4a-967c52172513)

A footer change shouldn't take so many line changes.

2024-05-19 04:28 UTC, mohit-bhandari45 commented
I have done the changes you can check

2024-05-19 15:49 UTC, adityaraute commented
> ![image](https://private-user-images.githubusercontent.com/151373021/328607104-560f1828-d73b-4102-a7ee-0281e36a7e93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMzM5OTQsIm5iZiI6MTcxNjEzMzY5NCwicGF0aCI6Ii8xNTEzNzMwMjEvMzI4NjA3MTA0LTU2MGYxODI4LWQ3M2ItNDEwMi1hN2VlLTAyODFlMzZhN2U5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOVQxNTQ4MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NDkwYzM4YzdlNzdhMDk4ZjhjZDIwNmJmYzQ3ZDJlZTQ2M2U0NDZhY2I1OTZhYThkZWExMzU2NWZhYjdhOWMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WAtleYArVeFavHxm7k8atGfrnPTWZ91zIcOCMp_rW1w) is it good now??



![image](https://github.com/rbjks/rbjks.github.io/assets/43912470/f79ca734-913f-4900-a57c-73057badfb6f)

The text in mobile view doesn't break at that exact point.
Also the icon is very close to the border.

2024-05-19 18:15 UTC, mohit-bhandari45 commented
I cannot do it

2024-05-20 18:01 UTC, adityaraute commented
> I cannot do it

Okay 1 cannot be solved.
Can 2 be solved? As in, can the icon be moved away from the left border?

2026-01-07 06:34 UTC, closed without merging