Enhancements: Updated README, certain changes done.
rbjks/rbjks.github.io pull request #141
Opened 2024-05-16 22:13 UTC by iemafzalhassan

## Motivation and Context

The motivation behind these changes was to enhance the visibility and engagement of the repository by updating the README.md file, adding social media account badges, and integrating a repository rater. These changes aim to make the repository more accessible to users and encourage interaction with its content.

## Description

- Updated the README.md file to provide a comprehensive overview of the repository, including its purpose, features, and usage instructions.
- Added badges linking to social media accounts (Facebook and Twitter) to facilitate direct access to the maintainer's profiles.
- Integrated a repository rater to gather feedback and ratings from users, enhancing the repository's credibility and trustworthiness.

## How Has This Been Tested?

These changes have been tested by:

- Reviewing the updated README.md file to ensure clarity and completeness of information.
- Clicking on the social media badges to confirm that they correctly link to the respective profiles.
- Interacting with the repository rater to validate its functionality and usability.

## Screenshots (if appropriate):

<img width="969" alt="Screenshot 2024-05-17 at 3 41 29 AM" src="https://github.com/rbjks/rbjks.github.io/assets/136967348/38cc501a-49a8-4ed7-b42a-b6f8cc3f43bc">

## Types of Changes

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

2024-05-17 08:29 UTC, adityaraute requested changes
I've made some suggestions.
Remember, the README is more for the repository and less for the NGO's functions. It should serve as a guide to our contributors first.

2024-05-17 08:29 UTC, adityaraute commented on assets/images/hero.png
Where is this screenshot from? The text on the right could be improved.

2024-05-17 08:29 UTC, adityaraute commented on README.md
> +  - **Call us:** +91 - 9418151074 / 8675300009
We don't need to mention the Phone numbers on the README file.

2024-05-17 08:29 UTC, adityaraute commented on README.md
> +[![RepoRater Badge](https://repo-rater.eddiehub.io/api/badge?owner=rbjks&name=rbjks.github.io)](https://repo-rater.eddiehub.io/rate?owner=rbjks&name=rbjks.github.io)
Please remove this badge as it is part of another issue.

2024-05-17 08:29 UTC, adityaraute commented on README.md
> +RBJKS, a distinguished non-profit organization headquartered in Nagpur, Himachal Pradesh, India, stands as a beacon of hope and progress for our local community. With a steadfast commitment to social
Use the full name instead of 'RBJKS'.
Also, it's Nurpur not Nagpur.

2024-05-17 08:29 UTC, adityaraute commented on README.md
> -![Deep Saffron](https://user-images.githubusercontent.com/115361239/220579735-fb87b37d-67f4-406c-8188-2d42f29f9847.png)
Please don't remove the color schemes as these are important to contributors. 
Perhaps we can add them as another section just below the Contact section?

2024-05-18 14:40 UTC, adityaraute approved these changes
This looks really good!

2024-05-18 14:41 UTC, merged

2024-05-18 14:41 UTC, adityaraute commented
Did you use any AI tool to generate the content?

2024-05-18 17:17 UTC, iemafzalhassan commented
Yup! took support from [chatGPT](https://chatgpt.com/?model=gpt-4o) and [blackBOX](https://www.blackbox.ai/)

2024-05-19 15:44 UTC, adityaraute commented
Cool, thanks for sharing.

2024-05-23 08:12 UTC, iemafzalhassan commented
**You're welcome** 🤗