Okello sam21 patch 1
rbjks/rbjks.github.io pull request #24
Opened 2023-03-01 12:16 UTC by OkelloSam21

2023-03-01 22:51 UTC, adityaraute commented
Hi @OkelloSam21

Not sure what this PR is as no file contents are changed here. Please mention the issue number in the comment or title of the PR as well, when you commit the necessary changes.

Marking the PR as draft for now.

2023-03-03 13:07 UTC, adityaraute commented
Hi @OkelloSam21 ,

Make sure that for the facebook icon you download the svg file which is in the same theme as the other icons.

2023-03-05 07:37 UTC, adityaraute requested changes
Looks like you didn't test it

2023-03-05 07:37 UTC, adityaraute commented on index.html
> +                    <a href="https://www.facebook.com/akil.bakhshi/"><img src="./assets/images/faccebook.svg" alt="facebook"></a>
```suggestion
                    <a href="https://www.facebook.com/akil.bakhshi/"><img src="./assets/images/facebook-f.svg" alt="facebook"></a>
```

2023-03-06 06:17 UTC, adityaraute requested changes
![image](https://user-images.githubusercontent.com/43912470/223033229-e7ae1bcb-969f-4437-a7ed-783dd4d237c4.png)


This is still not working. Please make the necessary change as I had suggested in my previous review.

2023-03-06 10:53 UTC, adityaraute commented
If you're still not sure what change to make, please ask.

2023-03-06 16:42 UTC, OkelloSam21 commented
> If you're still not sure what change to make, please ask.
Where should I change?

2023-03-06 18:49 UTC, adityaraute commented
> > If you're still not sure what change to make, please ask.
> > Where should I change?

Your svg filename is facebook-f.svg
HTML href name is faccebook.svg

That's causing the issue? make them both the same.

2023-03-07 20:07 UTC, OkelloSam21 commented
> > > If you're still not sure what change to make, please ask.
> > > Where should I change?
> 
> Your svg filename is facebook-f.svg HTML href name is faccebook.svg
> 
> That's causing the issue. Make them both the same.
here is my output...
![RBJKS__Home - Google Chrome 3_7_2023 10_52_38 PM (2)](https://user-images.githubusercontent.com/115361239/223538182-638b5a37-ceec-4dc6-a86e-a5010fabd7b8.png)

2023-03-07 20:07 UTC, OkelloSam21 commented
I think am done

2023-03-07 20:08 UTC, OkelloSam21 reviewed
Completed

2023-03-07 20:51 UTC, adityaraute commented
![image](https://user-images.githubusercontent.com/43912470/223549303-362643c7-abea-4337-a311-bb209a76fea1.png)


What do you mean your done? The href and the filename still do not match. Your svg file is named facebook-f.svg. Change it to facebook.svg and then it will work.

![image](https://user-images.githubusercontent.com/43912470/223549523-0fe27839-be0a-4a8c-b178-29b9524c3e9e.png)

I'm still seeing the error, are you not testing the changes on your end?

2023-03-07 21:33 UTC, OkelloSam21 reviewed
renamed Facebook-f.svg to Facebook.svg

2023-03-08 09:13 UTC, adityaraute requested changes
It still doesn't work my friend
You spelt facebook wrong
![image](https://user-images.githubusercontent.com/43912470/223671745-01514821-9ff2-4032-98da-d9330435a775.png)

![image](https://user-images.githubusercontent.com/43912470/223671776-fe57565d-afc1-4787-99e1-b9d39b8b3f45.png)


I've made a suggestion, you can commit that.

2023-03-08 09:13 UTC, adityaraute commented on index.html
> +                    <a href="https://www.facebook.com/akil.bakhshi/"><img src="./assets/images/faccebook.svg" alt="facebook"></a>
```suggestion
                    <a href="https://www.facebook.com/akil.bakhshi/"><img src="./assets/images/facebook.svg" alt="facebook"></a>
```

2023-03-08 16:26 UTC, OkelloSam21 commented
> ![image](https://user-images.githubusercontent.com/43912470/223549303-362643c7-abea-4337-a311-bb209a76fea1.png)
> 
> What do you mean your done? The href and the filename still do not match. Your svg file is named facebook-f.svg. Change it to facebook.svg and then it will work.
> 
> ![image](https://user-images.githubusercontent.com/43912470/223549523-0fe27839-be0a-4a8c-b178-29b9524c3e9e.png)
> 
> I'm still seeing the error, are you not testing the changes on your end?

I've committed your suggestion

2023-03-08 18:27 UTC, merged

2023-03-08 18:28 UTC, adityaraute commented
Great!

Are you new to open Source?

2023-03-09 19:16 UTC, OkelloSam21 commented
> Great!
> 
> Are you new to Open Source?

Yeah...In fact, this was my first opensource contribution

2023-03-10 10:34 UTC, adityaraute commented
Understandable.