This commit fixes #39
rbjks/rbjks.github.io pull request #41
Opened 2023-03-17 11:56 UTC by Kapoor-0905

Fixes #39 

Changes proposed 

- Contact Page changed
- Color scheme changed in nav bar and home.
-

Test Methodology and Results

- Responsive contact page with beautiful UI
-
-

2023-03-17 12:11 UTC, adityaraute requested changes

2023-03-17 12:11 UTC, adityaraute commented on assets/css/style.css
Can you reset these indentation changes? I'm setting up a linting action on another branch but these changes are not necessary here.

2023-03-17 12:11 UTC, adityaraute commented on assets/images/3.png
Delete unused images

2023-03-17 12:11 UTC, adityaraute commented on contactPage.html
Why didn't you make those changes in the previous file instead of creating a new one? This has broken the header links.

Also, would be great if you add the footer from the original homepage, here too.

2023-03-17 12:11 UTC, adityaraute commented on index.html
Here, too, I see some unnecessary linting changes. Please fix the same.

2023-03-17 12:15 UTC, Kapoor-0905 commented on contactPage.html
I have to make the contact form from scratch so I made a new file, and the header links, I have updated them.
Sure I will add the Footer here too.

2023-03-17 12:44 UTC, adityaraute commented on contactPage.html
Then I'd suggest renaming this as contact.html because it's semantically correct.

2023-03-17 13:42 UTC, adityaraute requested changes
Also, try to use the predefined theme colors everywhere possible

2023-03-17 13:42 UTC, adityaraute commented on activities.html
Again here we have linting, indentation, and styling changes. Please revert those.

2023-03-17 13:42 UTC, adityaraute commented on contactPage.html
rename as contact.html

2023-12-25 19:45 UTC, adityaraute commented
Merging this despite of a lack of response from the contributor

2023-12-25 19:46 UTC, merged