issue #78  use logo in header and footer
rbjks/rbjks.github.io pull request #80
Opened 2024-01-10 10:28 UTC by letsmailvjkumar

issue #78
added the log image location which was different.

2024-01-10 19:57 UTC, adityaraute commented
The issue is not linked to the PR by only mentioning it. You have to either use the term 'Fixes #' or link it on the right hand sidebar.
This is why we have PR templates in place.

2024-01-10 20:00 UTC, adityaraute requested changes
There are a few requested changes, please correct them; only then can the PR be merged.
Let us know if you need any help

2024-01-10 20:00 UTC, adityaraute commented on index.html
You are using the larger picture. You have to use the `favicon` image from the brand directory.

Additionally, you are only changing the logo on `index.html`. You should also change the logo on other webpages.

2024-01-11 03:15 UTC, letsmailvjkumar commented
Thanks for the detailed report. I will fixed it.

On Thu, Jan 11, 2024, 1:31 AM Aditya Raute ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> There are a few requested changes, please correct them; only then can the
> PR be merged.
> Let us know if you need any help
> ------------------------------
>
> On .vscode/settings.json
> <https://github.com/rbjks/rbjks.github.io/pull/80#discussion_r1447902428>:
>
> This change should not be committed. Please reverse this commit.
> ------------------------------
>
> On index.html
> <https://github.com/rbjks/rbjks.github.io/pull/80#discussion_r1447904260>:
>
> You are using the larger picture. You have to use the favicon image from
> the brand directory.
>
> Additionally, you are only changing the logo on index.html. You should
> also change the logo on other webpages.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/rbjks/rbjks.github.io/pull/80#pullrequestreview-1814061680>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3QD5FHL7HZRLMEBHB6H3G3YN3XQDAVCNFSM6AAAAABBURJUBWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQMJUGA3DCNRYGA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-01-11 10:20 UTC, closed without merging